DROP TABLE expression IF EXISTS;
DROP TABLE number IF EXISTS;
CREATE TABLE expression(id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, date TIMESTAMP, expression TEXT, solution DOUBLE);
CREATE TABLE number(value DOUBLE PRIMARY KEY, count INT);